name: Fetch JSON Data

on:
  schedule:
    -  cron: '0 20 * * 0' # 每个周日 UTC 时间 04:00 执行
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Fetch JSON data
        run: |
          curl https://notes-api.huisu.moe > src/resources/data.json

      - name: Save JSON data to repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout main
          git pull
          git add src/resources/data.json
          git commit -m "Update data.json"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
